//! # Classical Hebbian Learning (Pure STDP)
//! 
//! Honors Donald O. Hebb's 1949 principle: "Neurons that fire together wire together."
//! "When an axon of cell A is near enough to excite a cell B and repeatedly or persistently takes part in firing it,
//! some growth process or metabolic change takes place in one or both cells such that A's efficiency, as one of the cells firing B, is increased."
//! 
//! This module implements a pure (unmodulated) Spike-Timing-Dependent Plasticity (STDP) learning rule, which is a biologically inspired mechanism
//! for synaptic weight updates based on the precise timing of pre- and post-synaptic spikes.
//! Credit: Majority generated by Grok 4.20 Expert
use crate::izhikevich::IzhikevichNeuron;

/// Minimal Q88 fixed-point wrapper (stub for compilation)
#[derive(Clone, Copy, Debug)]
pub struct Q88(f32);
impl Q88 {
    pub fn from(v: f32) -> Self { Q88(v) }
    pub fn to_f32(&self) -> f32 { self.0 }
}

#[derive(Debug, Clone, Copy)]
pub struct StdpParams {
    pub a_plus: f32, // Maximum potentiation (LTP) amplitude
    pub a_minus: f32, // Maximum depression (LTD) amplitude
    pub tau_plus: f32, // Time constant for LTP (ms / steps)
    pub tau_minus: f32, // Time constant for LTD (ms / steps)
    pub w_min: f32, // Minimum synaptic weight
    pub w_max: f32, // Maximum synaptic weight
}

impl Default for StdpParams {
    fn default() -> Self {
        Self {
            a_plus: 0.01, // Typical LTP amplitude
            a_minus: 0.012, // Slightly stronger LTD for stability
            tau_plus: 20.0, // Typical LTP time constant (ms / steps)
            tau_minus: 20.0, // Typical LTD time constant (ms / steps)
            w_min: 0.0, // No negative weights (no inhibitory synapses in this simple model)
            w_max: 2.0, // Maximum weight to prevent runaway excitation
        }
    }
}

/// Pure Hebbian STDP update function (no reward/neuromodulator multiplayer)
/// This function calculates the weight change based on the timing of pre- and post-synaptic spikes.
pub fn apply_classical_stdp(pre_spike_time: i64, post_spike_time: i64, current_weight: f32, params: &StdpParams) -> f32 { // Calculate the time difference between pre and post spikes
    let delta_t = post_spike_time - pre_spike_time; // Time difference in ms / steps
    let weight_change = if delta_t > 0 {
        // Pre before post → LTP
        params.a_plus * (-delta_t as f32 / params.tau_plus).exp()
    } else if delta_t < 0 {
        // Post before pre → LTD
        -params.a_minus * (delta_t as f32 / params.tau_minus).exp()
    } else {
        0.0 // No change if they spike at the same time
    };
    
    // Update weight and clip to bounds
    let new_weight = (current_weight + weight_change).clamp(params.w_min, params.w_max);
    new_weight
}

/// Example: Small Izhikevich + pure Hebbian network with classical STDP learning
/// This is a simple demonstration of how to use the apply_classical_stpd function in a network context. In a real implementation, you would integrate
/// this into the learning loop of your SpikingNetwork engine, where you would track pre/post spike times and update synaptic weights accordingly.
pub struct HebbianIzhikevichNetwork {
    pub neurons: Vec<IzhikevichNeuron>,
    pub weights: Vec<Q88>, // Synaptic weights between neurons
    pub stdp_params: StdpParams, // STDP hyperparameters
}

// In a real implementation, you would also need to define the network architecture (which neurons connect to which) and ensure that spike times are properly tracked during the simulation step for accurate STDP updates.
impl HebbianIzhikevichNetwork {
    pub fn new(num_neurons: usize) -> Self { // Initialize a network with a given number of neurons and random weights
        let neurons = (0..num_neurons).map(|_| IzhikevichNeuron::new_regular_spiking()).collect(); //   Initialize neurons (you could also create a mix of neuron types)
        let weights = vec![Q88::from(0.5); num_neurons * num_neurons]; // Initialize weights to 0.5
        Self { neurons, weights, stdp_params: StdpParams::default() } // In a real implementation, you would likely want to initialize weights more carefully (e.g., random small values) and set up the network architecture (which neurons connect to which).
    }
    
    /// This function would be called during the learning phase after each simulation step to update weights based on spike timings.
    pub fn update_weights(&mut self, pre_index: usize, post_index: usize) { // You would need to ensure that pre_index and post_index are valid indices for your neuron population
        let pre_spike_time = self.neurons[pre_index].last_spike_time; // You would need to ensure that last_spike_time is properly updated in your neuron model during the simulation step.
        let post_spike_time = self.neurons[post_index].last_spike_time; // Same as above, ensure this is updated correctly during the simulation step.
        let current_weight = self.weights[pre_index * self.neurons.len() + post_index].to_f32(); // Convert Q88 to f32 for calculation
        // Calculate the new weight using the classical STDP function
        let new_weight = apply_classical_stdp(pre_spike_time, post_spike_time, current_weight, &self.stdp_params); // Calculate the new weight using the STDP function
        self.weights[pre_index * self.neurons.len() + post_index] = Q88::from(new_weight); // Convert back to Q88
    }
}