//! Pure 1907 Lapicque Integrate-and-Fire neuron model, which is the biological root of all spiking neuron models.
//! This is the simplest possible spiking neuron model, and serves as a baseline for more complex models like Izhikevich and Hodgkin-Huxley.
//! It captures the essential "integrate and fire" behavior of neurons, where the membrane potential integrates incoming stimuli and fires a spike when a threshold is reached, followed by a reset. 
//! This model is computationally efficient and can be used for large-scale simulations where biological realism is less critical, or as a building block for more complex models.|
//! It is also a useful educational tool for understanding the fundamental principles of spiking neuron dynamics and synaptic plasticity. 
//! The LIF model is often used in neuromorphic hardware implementations due to its simplicity and efficiency, making it a key component in the development of energy-efficient spiking neural networks for applications like pattern recognition, sensory processing, and reinforcement learning.
//!  In the context of this crate, the LIF neuron serves as a fast, reactive component that can be used in conjunction with more complex Izhikevich neurons and reward-modulated STDP learning rules to create a versatile and biologically-inspired spiking neural network engine.
//! The LIF model is defined by a simple differential equation that describes how the membrane potential changes over time in response to incoming stimuli and passive decay. When the membrane potential reaches a certain threshold, the neuron fires a spike and resets its potential, simulating the refractory period observed in biological neurons.
//! Reference: Lapicque, L. (1907). Recherches quantitatives sur l'excitation électrique des nerfs traitée comme une polarisation. Journal de Physiologie et de Pathologie Générale, 9, 620–635.
//! Note: The original codebase had a more complex neuron model with plasticity, but this LIF implementation is a simplified version that focuses on the core integrate-and-fire dynamics without the additional complexity of the original model.
//! The weights and plasticity mechanisms will be handled separately in the reward-modulated  STDP module, allowing us to keep the LIF neuron model clean and focused on its core functionality. This separation of concerns also makes it easier to modify or extend the neuron model in the future without affecting the learning rules, and vice versa. 
//! The LIF neuron can be used as a building block in larger networks where different types of neurons (e.g., Izhikevich) can be combined to create a rich diversity of firing patterns and computational capabilities, while still maintaining the simplicity and efficiency of the LIF model for certain parts of the network that require fast, reactive behavior.
//! The LIF model is also a useful tool for studying the effects of synaptic inputs and neuromodulators on neuronal firing patterns, as it allows us to easily manipulate the membrane potential and threshold dynamics in response to different stimuli and modulatory signals, providing insights into how neurons process information and adapt their behavior in response to changing conditions.
//! The LIF neuron can also be used in conjunction with the reward-modulated STDP learning rules to create a simple yet powerful learning system that can adapt its synaptic weights based on the timing of pre- and post-synaptic spikes and the presence of reward signals, allowing us to explore the principles of reinforcement learning and synaptic plasticity in a biologically-inspired context.
//! The LIF model is a fundamental component of many neuromorphic computing systems and spiking neural network simulations, and serves as a key building block for understanding the dynamics of spiking neurons and their role in information processing and learning in the brain.
//!  By implementing the LIF neuron model in this crate, we provide a simple and efficient tool for simulating spiking neural networks and exploring the principles of neuronal dynamics and synaptic plasticity in a biologically-inspired context, while also laying the groundwork for more complex models and learning rules that can be built on top of this foundational neuron model.
//! The LIF neuron model is defined by the following equations:
//! dv/dt = -(v - v_rest) / tau + I(t) / C 
//! Where v is the membrane potential, v_rest is the resting potential, tau is the membrane time constant, I(t) is the input current, and C is the membrane capacitance. When v reaches a threshold value (v_threshold), the neuron fires a spike and resets its potential to a reset value (v_reset), simulating the refractory period observed in biological neurons.   
//! Credit: Majority generated by Grok 4.20 Expert
use serde::{Deserialize, Serialize}; // We will use serde for easy serialization and deserialization of neuron states, which is useful for saving/loading models and for debugging purposes.

#[derive(Clone, Serialize, Deserialize, Debug)] // Deriving Clone, Serialize, Deserialize, and Debug traits for easy copying, serialization, and debugging of neuron instances.
pub struct LapicqueNeuron { // State variables and parameters for the LIF neuron model
    pub membrane_potential: f32, // Current charge state
    pub decay_rate: f32,         // How fast it "forgets" (Leak)
    pub threshold: f32,          // Limit to trigger an action potential
    pub base_threshold: f32,     // Resting threshold for dynamic modulation
    pub last_spike: bool,        // Tracks if it fired in the last step
    pub weights: Vec<f32>,      // Synaptic weights for each input channel
    pub last_spike_time: i64,   // Timestep of the most recent spike
}

impl Default for LapicqueNeuron { // Default values for the LIF neuron parameters and state
    fn default() -> Self { // Default values for the LIF neuron parameters and state
        Self { // Default values for the LIF neuron parameters and state
            membrane_potential: 0.0, // Start at resting potential
            decay_rate: 0.15, // Decay rate for the leak (15% per step)
            threshold: 0.02,  // Aggressively lowered threshold for more responsive firing
            base_threshold: 0.02, // Store the base threshold for dynamic modulation by inhibitory interneurons
            last_spike: false, // Initially, the neuron has not fired
            weights: Vec::new(), // Weights will be initialized later based on the number of input channels
            last_spike_time: -1, // No spikes have occurred yet, so we set this to -1 to indicate that
        }
    }
}

impl LapicqueNeuron { // Constructor for creating a new LIF neuron instance with default parameters
    pub fn new() -> Self { // Constructor for creating a new LIF neuron instance with default parameters
        Self::default() // Constructor for creating a new LIF neuron instance with default parameters
    }

    /// The Core Logic Step:
    /// 1. Add Input (Integration)
    /// 2. Lose Charge (Leak)
    pub fn integrate(&mut self, stimulus: f32) { // Integrate incoming stimulus and apply leak to the membrane potential
        // CHARGE: Add input stimulus to current state
        self.membrane_potential += stimulus;
        // LEAK: Decay towards resting potential (0.0) at the specified decay rate
        self.membrane_potential *= 1.0 - self.decay_rate;
    }

    /// Check if the neuron fires a spike based on the current membrane potential and threshold.
    /// If it fires, reset the membrane potential and update the last spike time.
    pub fn check_for_spike(&mut self, current_time: i64) -> bool { // Returns true if the neuron fired a spike, false otherwise
        let mut spikes = false; // Check if the membrane potential has reached or exceeded the threshold
        if self.membrane_potential >= self.threshold { // FIRE: Reset membrane potential and record spike time
            // FIRE: Reset membrane potential and record spike time
            self.membrane_potential = 0.0; // Reset to resting potential after firing
            self.last_spike = true; // Mark that the neuron fired in this step
            self.last_spike_time = current_time; // Update last spike time for STDP calculations
            spikes = true; // Indicate that a spike occurred
        } else { // No spike this step
            self.last_spike = false; // No spike this step
        }
        spikes // Return whether a spike occurred
    }
}